[CMOB-1308] Feature:  Setup send message logic
georgemakadze/ChatApp pull request #2
Opened 2023-05-02 10:00 UTC by georgemakadze

1. I added logic that separates the text bubbles correctly with the date text.
2. Separately, I exported the fake data text, which is of array type.
3. I made an enum that has two cases, the sender me and the other one. To define user texts for both views (myMessageView, otherMessageView).
4. Add message send logic.
5. Add Core Data.
6. Add Reachability.
7. Add Keyboard.

<img width="292" alt="Screenshot 2023-05-02 at 13 59 26" src="https://user-images.githubusercontent.com/111285282/235637351-46892fa3-c144-41da-81fd-f574465fe2ef.png">

2023-05-03 01:07 UTC, datoberdznishvili requested changes

2023-05-03 01:07 UTC, datoberdznishvili commented on ChatApp/ChatView/ChatViewController.swift
> +    var isDarkMode = false
ეს რატომ არ არის private?

2023-05-03 01:07 UTC, datoberdznishvili commented on ChatApp/ChatView/ChatViewController.swift
> +    private var stackView: UIStackView!
სხვა კომპონენტებისნაირად ამის ინიციალიზება რატომ არ ხდება აქ? შეეცადე consistency დაიცვა და ისედაც აქვე რომ გაგეკეთებინა let იქნებოდა და წასაკითხადაც უფრო მარტივი

2023-05-03 01:07 UTC, datoberdznishvili commented on ChatApp/ChatView/ChatViewController.swift
> +        modeButton.setImage(UIImage(named: "darkmode"), for: .normal)
კონსტანტებში გაიტანე ისეთი რაღაცეები როგორიც არის: ფოტოები, ტექსტები, ფერები...
ეს issue ბევრგან გაქვს, და ყველგან არ დაგიწერ;

2023-05-03 01:07 UTC, datoberdznishvili commented on ChatApp/ChatView/ChatViewController.swift
> +        isDarkMode = !isDarkMode
isDarkMode.toggle() შეგიძლია გამოიყენო

2023-05-03 01:07 UTC, datoberdznishvili commented on ChatApp/ChatView/ChatViewController.swift
> +    @objc private func switchMode() {
ფუნქციისთვის არ არის კარგი სახელი, შეეცადე action nameბი დაარქვა

2023-05-03 01:07 UTC, datoberdznishvili commented on ChatApp/ChatView/ChatViewController.swift
> +    }
შეგიძლია გააერთიანო ეს ორი მეთოდი და რამე custom enum ან flag გადააწოდო

2023-05-03 01:07 UTC, datoberdznishvili commented on ChatApp/ChatView/MessageCell.swift
> +    //    let label2 = UILabel()
ამ ფაილში ბევრი დაკომენტარებული კოდი გაქვს, თუ აღარ არის საჭირო წაშალე

2023-05-03 01:07 UTC, datoberdznishvili commented on ChatApp/ChatView/MessageCell.swift
> +        label.font = UIFont.systemFont(ofSize: CGFloat(Constants.labelFontSize))
Type inference იხმარე, 
```suggestion
        label.font = .systemFont(ofSize: CGFloat(Constants.labelFontSize))
```

2023-05-03 01:07 UTC, datoberdznishvili commented on ChatApp/ChatView/MessageView.swift
> +            case.Other:
```suggestion
            case. Other:
```

2023-05-03 01:07 UTC, datoberdznishvili commented on ChatApp/ChatView/Messages.swift
> +    }
არ გჭირდება ეს კონსტრუქტორი

2023-05-03 01:07 UTC, datoberdznishvili commented on ChatApp/ChatView/Messages.swift
> +    case Other
ქეისები lowercased

2023-05-03 01:07 UTC, datoberdznishvili commented on ChatApp/ChatView/MessageView.swift
> +        static let containerViewBottomAnchor = -16
ესეთ ქეისებში შეგიძლია გააკეთო ერთი პარამეტრი მაგ. collectionViewPadding = 16 და კოდში ან collectionViewPadding ან -collectionViewPadding გამოიყენო

2023-05-03 01:07 UTC, datoberdznishvili commented on ChatApp/ChatView/MessageView.swift
> +    }
ჯობია ეს კონსტანტები ერთად რომ არ გქონდეს ჩაყრილი, გაყო ლოგიკურად ცალკე  entityებში

2023-05-03 01:07 UTC, datoberdznishvili commented on ChatApp/ChatView/MessageView.swift
> +        static let textViewFont = 16
fontSize იგულისხმება ალბათ, კონსტანტების სახელებსაც მიაქციე ყურადღება

2023-05-03 01:07 UTC, datoberdznishvili commented on ChatApp/ChatView/MessageView.swift
> +    }
ესეც შეგიძლია გააერთიანო

2023-05-03 01:07 UTC, datoberdznishvili commented on ChatApp/ChatView/MessageView.swift
> +        snapshot = NSDiffableDataSourceSnapshot<Section, Message>()
1 ხაზზე გააერთიანე

2023-05-03 01:07 UTC, datoberdznishvili commented on ChatApp/ChatView/MessageView.swift
> +    private var dataSource: UICollectionViewDiffableDataSource<Section, Message>!
ჯობია აქვე მოხდეს ინიციალიზება

2023-05-03 01:07 UTC, datoberdznishvili commented on ChatApp/ChatView/MessageCell.swift
> +    }
ეს როგორც მივხვდი არის receiverის და სენდერის მიხედვით ლეიაუთის შეცვლა და ჯობია სახელი შეუცვალო + გააერთიანო

2023-05-03 01:07 UTC, datoberdznishvili commented on ChatApp/ChatView/MessageCell.swift
> +        fatalError("nope!")
fatalErrorების დროს ეცადე აზრიანი მესიჯი გადმოსცე

2023-05-03 01:07 UTC, datoberdznishvili commented on ChatApp/ChatView/ChatViewController.swift
> +        }
Ternaryთ შეგიძლია ერთ ხაზზე ჩაატიო

2023-05-03 01:07 UTC, datoberdznishvili commented on ChatApp/ChatView/ChatViewController.swift
> +class ChatViewController: UIViewController {
ყველა ფუნქცია ამ კლასშიც, და სხვა კლასებშიც გაქვს ერთად ჩაყრილი; ჯობია ლოგიკურად გაყო და კომენტარები მიაწერო (MARK: )

2023-05-03 01:07 UTC, datoberdznishvili commented on ChatApp/ChatView/ChatViewController.swift
> +    private let chatViewModel = ChatViewModel()
viewModelის ინსტანსი კლასში არ უნდა იქმნებოდეს და უნდა ჩააწოდო viewControllerის კონსტრუქციის დროს

2023-05-03 01:07 UTC, datoberdznishvili commented on ChatApp/ChatView/ChatViewModel.swift
> +class ChatViewModel {
ViewModel გაქვს გაგებული არასწორად, ამ კლასში უნდა იყოს ბიზნეს-ლოგიკა; შენ შემთხვევაში მაგ. ტექსტების გაგზავნა მოდელში უნდა მოხდეს აქედან, და Datasourceს დაბაინდინგებით უნდა დააფდეითდეს გვერდი

2023-05-03 01:07 UTC, datoberdznishvili commented on ChatApp/ChatView/MessageCell.swift
> +    let textDate = UILabel()
ჯობია ეს კომპონენტები იყოს private და გააკეთო ფუნქცია რომელიც მიიღებს სტრინგს და დასეტავს კომპონენტებზე

2023-05-04 08:34 UTC, georgemakadze commented on ChatApp/ChatView/MessageView.swift
> +    private var dataSource: UICollectionViewDiffableDataSource<Section, Message>!
collectionView ინიციალიზებას სჭირდება bounds da listLayout. ან lazy  var-ებად უნდა გადავაკეთო ან ესე უნდა დავტოვო და რას ფიქრობ?

2023-05-08 08:08 UTC, datoberdznishvili commented on ChatApp/ChatView/MessageView.swift
> +    private var dataSource: UICollectionViewDiffableDataSource<Section, Message>!
პარამეტრების ინიციალიზების გაყოფას lazy ჯობია;
ზოგადად შეეცადე რო ლოგიკურად გქონდეს კოდი დაგრუპული

2023-05-29 07:06 UTC, giomatiashvilispace commented on ChatApp/Scenes/ChatView/MessageCell.swift
> +        if item.hasFailed == true {
აქ == true არ გჭირდება, if item.hasFailed {} აჯობებს

2023-05-29 07:10 UTC, giomatiashvilispace commented on ChatApp/Scenes/ChatView/MessageCell.swift
> +        }
1. აქ == true არ გჭირდება, if item.hasFailed {} აჯობებს
2. formatDAte() რომ გადააკეთო აჯობებს formatDate()
3. inliine if else თიც შეიზლება ამის დაწერა, textDate.text = item.hasFailed ? "არ გაიგზავნა" : item.date.formatDAte()

2023-05-29 07:13 UTC, giomatiashvilispace requested changes
პატარა ცვლილებებია გასაკეთებელი MessageCell.swift ში

2023-05-29 07:28 UTC, giomatiashvilispace approved these changes

2023-06-02 09:00 UTC, merged